# مراحل ConversationHandler
(
    MENU, TITLE, DESCRIPTION, MAIN_IMAGE, GALLERY_IMAGES, SIZES, COLOR, UPPER, SOLE, USAGE,
    SKU, PRICE, TAGS, BRAND, CONFIRM, EDIT_SKU, EDIT_CHOICE, EDIT_PRICE, EDIT_STOCK_MODE,
    EDIT_STOCK_UNIFORM, EDIT_STOCK_ARRAY, LINK_PRODUCTS
) = range(22)

# سایر ثابت‌ها (در صورت نیاز بعداً اضافه می‌کنیم)